name: musf_app1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.0.0
  curved_navigation_bar: ^1.0.3
  url_launcher: ^6.1.20 # Or latest version
  image_picker: ^0.8.7+4
  shared_preferences: ^2.0.18
  cupertino_icons: ^1.0.8
  flutter_svg: any
  share_plus: any
  animate_do: ^3.0.2
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  font_awesome_flutter: ^10.0.0
  gif_view: ^1.0.0
  firebase_remote_config: ^5.4.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/
    - assets/ad Banner/
    - assets/carrousel banner/